crm/common/models/Orders.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property string $id
 * @property string $customer_id
 * @property string $agent_id
 * @property string $writer_id
 * @property string $status
 * @property string $total_amount
 * @property string $paper_type_id
 * @property string $service_type_id
 * @property string $order_date
 * @property string $urgency_id
 * @property string $customer_deadline
 * @property string $quality_id
 * @property string $no_pages_id
 * @property string $subject_area_id
 * @property string $topic
 * @property string $acadamic_level_id
 * @property string $writing_style_id
 * @property string $language
 * @property int $referances
 * @property string $instructions
 * @property string $payment_method
 * @property string $writer_deadline
 *
 * @property Customers $customer
 * @property WritingStyles $writingStyle
 * @property User $agent
 * @property User $writer
 * @property PaperTypes $paperType
 * @property ServiceTypes $serviceType
 * @property NoPages $noPages
 * @property QualityLevels $quality
 * @property SubjectsAreas $subjectArea
 * @property AcademicLevels $acadamicLevel
 * @property Urgency $urgency
 *
 * @property Transactions[] $transactions
 * @property WriterTasks[] $writerTasks
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['total_amount', 'paper_type_id', 'service_type_id', 'order_date', 'urgency_id', 'customer_deadline', 'quality_id', 'no_pages_id', 'subject_area_id', 'topic', 'acadamic_level_id', 'writing_style_id', 'instructions', 'payment_method'], 'required'],
            [['customer_id', 'agent_id', 'writer_id', 'paper_type_id', 'service_type_id', 'urgency_id', 'quality_id', 'no_pages_id', 'subject_area_id', 'acadamic_level_id', 'writing_style_id', 'referances'], 'integer'],
            [['status', 'topic', 'instructions', 'payment_method'], 'string'],
            [['total_amount'], 'number'],
            [['order_date', 'customer_deadline', 'writer_deadline'], 'safe'],
            [['language'], 'string', 'max' => 150],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customers::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['writing_style_id'], 'exist', 'skipOnError' => true, 'targetClass' => WritingStyles::className(), 'targetAttribute' => ['writing_style_id' => 'id']],
            [['agent_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['agent_id' => 'id']],
            [['writer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['writer_id' => 'id']],
            [['paper_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => PaperTypes::className(), 'targetAttribute' => ['paper_type_id' => 'id']],
            [['service_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => ServiceTypes::className(), 'targetAttribute' => ['service_type_id' => 'id']],
            [['no_pages_id'], 'exist', 'skipOnError' => true, 'targetClass' => NoPages::className(), 'targetAttribute' => ['no_pages_id' => 'id']],
            [['quality_id'], 'exist', 'skipOnError' => true, 'targetClass' => QualityLevels::className(), 'targetAttribute' => ['quality_id' => 'id']],
            [['subject_area_id'], 'exist', 'skipOnError' => true, 'targetClass' => SubjectsAreas::className(), 'targetAttribute' => ['subject_area_id' => 'id']],
            [['acadamic_level_id'], 'exist', 'skipOnError' => true, 'targetClass' => AcademicLevels::className(), 'targetAttribute' => ['acadamic_level_id' => 'id']],
            [['urgency_id'], 'exist', 'skipOnError' => true, 'targetClass' => Urgency::className(), 'targetAttribute' => ['urgency_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'agent_id' => 'Agent ID',
            'writer_id' => 'Writer ID',
            'status' => 'Status',
            'total_amount' => 'Total Amount',
            'paper_type_id' => 'Paper Type',
            'service_type_id' => 'Service Type',
            'order_date' => 'Order Date',
            'urgency_id' => 'Urgency',
            'customer_deadline' => 'Customer Deadline',
            'quality_id' => 'Quality',
            'no_pages_id' => 'Num of Pages',
            'subject_area_id' => 'Subject Area',
            'topic' => 'Topic',
            'acadamic_level_id' => 'Academic Level',
            'writing_style_id' => 'Writing Style',
            'language' => 'Language',
            'referances' => 'References',
            'instructions' => 'Instructions',
            'payment_method' => 'Payment Method',
            'writer_deadline' => 'Writer Deadline',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customers::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWritingStyle()
    {
        return $this->hasOne(WritingStyles::className(), ['id' => 'writing_style_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgent()
    {
        return $this->hasOne(User::className(), ['id' => 'agent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWriter()
    {
        return $this->hasOne(User::className(), ['id' => 'writer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaperType()
    {
        return $this->hasOne(PaperTypes::className(), ['id' => 'paper_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceType()
    {
        return $this->hasOne(ServiceTypes::className(), ['id' => 'service_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNoPages()
    {
        return $this->hasOne(NoPages::className(), ['id' => 'no_pages_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuality()
    {
        return $this->hasOne(QualityLevels::className(), ['id' => 'quality_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjectArea()
    {
        return $this->hasOne(SubjectsAreas::className(), ['id' => 'subject_area_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcadamicLevel()
    {
        return $this->hasOne(AcademicLevels::className(), ['id' => 'acadamic_level_id']);
    }

    public function getUrgency()
    {
        return $this->hasOne(Urgency::className(), ['id' => 'urgency_id']);
    }
    public function getTransactions()
    {
        return $this->hasMany(Transactions::className(), ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWriterTasks()
    {
        return $this->hasMany(WriterTasks::className(), ['order_id' => 'id']);
    }

}

crm/backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use common\models\Customers;
use common\models\EmailTemplates;
use common\models\Transactions;
use common\models\User;
use common\models\WriterTasks;
use Yii;
use common\models\Orders;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class OrderController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionView()
    {
        $ordrId = \Yii::$app->request->get('id');
        $order = Orders::find()->where(['id' => $ordrId])->one();
        $customer = Customers::find()->where(['id' => $order->customer_id])->one();
        $inv = Transactions::find()->where(['order_id' => $ordrId])->one();
        if ($ordrId) {
            return $this->render('view', ['id' => $ordrId, 'o' => $order, 'c' => $customer, 't' => $inv]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAgentView()
    {
        $ordrId = \Yii::$app->request->get('id');
        $order = Orders::find()->where(['id' => $ordrId])->one();
        $customer = Customers::find()->where(['id' => $order->customer_id])->one();
        $inv = Transactions::find()->where(['order_id' => $ordrId])->one();
        if ($ordrId) {
            return $this->render('agent-view', ['id' => $ordrId, 'o' => $order, 'c' => $customer, 't' => $inv]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionEdit($id)
    {
        $model = Orders::find()->where(['id' => $id])->one();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/site/index']);
        }

        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    public function actionWriterAssign($id)
    {
        $order = Orders::find()->where(['id' => $id])->one();
        if ($id) {
            if(Yii::$app->request->post())
            {
                $wid = Yii::$app->request->post('writer_id');
                $rate = Yii::$app->request->post('rate_price');
                $wdeadline = Yii::$app->request->post('submission_date');
                $pc = Yii::$app->request->post('payment_cond');

                $order->writer_id = $wid;
                $order->writer_deadline = $wdeadline;
                $order->status = 'in_progress';
                $order->save(false);
                // update rate for writer
                $task = WriterTasks::find()->where(['writer_id'=>$wid,'order_id'=>$id])->one();
                if(!$task)
                    $task = new WriterTasks();
                $task->writer_id = $wid;
                $task->order_id  = $id;
                $task->task_rate = $rate;
                $task->payment_condition = ($pc == '1') ? 'Fixed' : 'Per Page';
                $task->submission_date = $wdeadline;
                $task->save(false);

                // send email to client for new order
                $et = new EmailTemplates();
                $et->order = $order;
                $et->type = 'task_assign_to_writer';
                $et->sendEmails();
                return $this->redirect(['/site/index']);
            }
            return $this->render('writer-assign', ['id' => $id, 'o' => $order]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionAgentAssign($id)
    {
        $order = Orders::find()->where(['id' => $id])->one();
        if ($id) {
            if(Yii::$app->request->post())
            {
                $aid = Yii::$app->request->post('agent_id');

                $order->agent_id = $aid;
                $order->status = 'pending';
                $order->save(false);
                // send email to client for new order
                $et = new EmailTemplates();
                $et->order = $order;
                $et->customer =  $order->customer;
                $et->type = 'client_intro';
                $et->sendEmails();
                return $this->redirect(['/site/index']);
            }
            return $this->render('agent-assign', ['id' => $id, 'o' => $order]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAgentPick($id)
    {
        $order = Orders::find()->where(['id' => $id])->one();
        if ($id) {
            $aid = Yii::$app->user->id;

            $order->agent_id = $aid;
            $order->status = 'pending';
            $order->save(false);
            // send email to client for new order
            $et = new EmailTemplates();
            $et->order = $order;
            $et->customer =  $order->customer;
            $et->type = 'client_intro';
            $et->sendEmails();
            return $this->redirect(['/site/index']);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAssignUpdate($id)
    {
        $order = Orders::find()->where(['id' => $id])->one();
        if ($id) {
            $task = WriterTasks::find()->where(['order_id'=>$id])->one();
            if(Yii::$app->request->post())
            {
                $wid = Yii::$app->request->post('writer_id');
                $rate = Yii::$app->request->post('rate_price');
                $wdeadline = Yii::$app->request->post('submission_date');
                $pc = Yii::$app->request->post('payment_cond');
                $status = Yii::$app->request->post('status');

                $order->writer_id = $wid;
                $order->writer_deadline = $wdeadline;
                $order->status = 'in_progress';
                $order->save(false);
                // update rate for writer
                $task = WriterTasks::find()->where(['writer_id'=>$task->writer_id,'order_id'=>$id])->one();
                $task->writer_id = $wid;
                $task->task_rate = $rate;
                $task->payment_condition = ($pc == '1') ? 'Fixed' : 'Per Page';
                $task->status = $status;
                $task->submission_date = $wdeadline;
                $task->save(false);

                return $this->redirect(['/site/index']);
            }
            return $this->render('update-assign', ['id' => $id, 'o' => $order,'t'=>$task]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPending()
    {
        return $this->render('pending');
    }

    public function actionProcess()
    {
        return $this->render('process');
    }

}

crm/backend/views/order/agent-assign.php
<?php
/**
 * Created by PhpStorm.
 * User: umerz
 * Date: 9/22/2018
 * Time: 1:47 PM
 */
use common\models\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Agent Assigning for Order#' . $id;
$this->params['breadcrumbs'][] = ['label' => 'Dashboard', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = $this->title;


$agentsList = ArrayHelper::map(User::find()->where(['role_id' => User::ROLE_CSR])->asArray()->all(), 'id', 'full_name');
?>
<?php $form = ActiveForm::begin(['id' => 'w_form']); ?>
    <div class="card">
        <div class="card-body">
            <h4>Assign Task to Agent - Order #<?= $id ?></h4>
            <br>
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group required">
                        <label class="control-label" for="orders-topic">Assign Order To:</label>
                        <?= Html::dropDownList('agent_id', [], $agentsList, ['prompt' => 'Select Agents', 'class' => 'form-control', 'required' => 'required', 'id' => 'agent_id']) ?>
                        <div class="help-block we"></div>
                    </div>
                </div>


            </div>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group float-none">
                        <br>
                        <?= Html::submitButton('Assign Task', ['class' => 'btn btn-success']) ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
<?php ActiveForm::end(); ?>

crm/backend/views/order/agent-view.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;


$this->title = 'Order View #'.$id;
$this->params['breadcrumbs'][] = ['label' => 'Dashboard', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Basic Order Information</h4>
        <table class="table color-bordered-table success-bordered-table">
            <tr>
                <th>Order Id</th>
                <td><?=$o->id?></td>
            </tr>
            <tr>
                <th>Paper Type</th>
                <td><?=$o->paperType->name?></td>
            </tr>
                <th>Service Type</th>
                <td><?=$o->serviceType->name?></td>
            </tr>
            <tr>
                <th>Order Date</th>
                <td><?=$o->order_date?></td>
            </tr>
            <tr>
                <th>Urgency</th>
                <td><?=$o->urgency->name?></td>
            </tr>
            <tr>
                <th>Customer Deadline</th>
                <td><?=\backend\util\Help::getCustomerDealLine($o->urgency_id)?></td>
            </tr>
            <tr>
                <th>Quality</th>
                <td><?=$o->quality->name?></td>
            </tr>
            <tr>
                <th>Num of Pages</th>
                <td><?=$o->noPages->name?></td>
            </tr>
            <tr>
                <th>Subject</th>
                <td><?=$o->subjectArea->name?></td>
            </tr>
            <tr>
                <th>Topic</th>
                <td><?=$o->topic?></td>
            </tr>
            <tr>
                <th>Level</th>
                <td><?=$o->acadamicLevel->name?></td>
            </tr>
            <tr>
                <th>Writing Style</th>
                <td><?=$o->writingStyle->name?></td>
            </tr>
            <tr>
                <th>Language</th>
                <td><?=$o->language?></td>
            </tr>
            <tr>
                <th>Description</th>
                <td><?=$o->instructions?></td>
            </tr>


        </table>

    </div>
</div>

<div class="card">
    <div class="card-body">
    <h4 class="card-title">Client Information - Order # <?=$id?></h4>
        <table class="table color-bordered-table success-bordered-table">
            <tr>
                <th>Client Id</th>
                <td><?=$c->id?></td>
            </tr>
            <tr>
                <th>Customer Name</th>
                <td><?=$c->name?></td>
            </tr>
                <th>Customer Email</th>
                <td><?=$c->email?></td>
            </tr>
            <tr>
                <th>Customer Phone</th>
                <td><?=$c->phone?></td>
            </tr>
            <tr>
                <th>Customer IP</th>
                <td><?=$c->ip?></td>
            </tr>
            <tr>
                <th>Customer IP-City</th>
                <td><?=$c->city?></td>
            </tr>
            <tr>
                <th>Customer IP-Region</th>
                <td><?=$c->region?></td>
            </tr>
            <tr>
                <th>Customer IP-Country</th>
                <td><?=$c->country?></td>
            </tr>
            <tr>
                <th>Customer Registration </th>
                <td><?=$c->created_at?></td>
            </tr>


        </table>

    </div>
</div>

crm/backend/views/order/pending.php
<?php
use backend\util\Help;

$this->title = 'Pending Orders';
#$this->params['breadcrumbs'][] = ['label' => 'Dashboard', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = 'Dashboard';
$pendingOrders = \common\models\Orders::find()->where(['status'=>'pending'])->all();

?>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Pending Works</h4>
        <div class="table-responsive">
            <table class="table color-bordered-table warning-bordered-table">
                <thead>
                <tr>
                    <th>Order #</th>
                    <th>Customer Name</th>
                    <th>Topic</th>
                    <th>Subject Area</th>
                    <th>Service</th>
                    <th>Status</th>
                    <th>Pages</th>
                    <th>Agent</th>
                    <th>Customer Deadline</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($pendingOrders as $o): ?>
                <tr>
                    <td><?= $o->id ?></td>
                    <td><?= $o->customer->name ?></td>
                    <td><?= $o->topic ?></td>
                    <td><?= $o->subjectArea->name ?></td>
                    <td><?= $o->serviceType->name ?></td>
                    <td><span class="badge badge-warning"><?= $o->status ?></span></td>
                    <td><?= $o->noPages->name ?></td>
                    <td><?= $o->agent->full_name ?></td>
                    <td><?= Help::getCustomerDealLine($o->urgency_id) ?></td>
                    <td><a href="<?= \yii\helpers\Url::to(['order/writer-assign', 'id' => $o->id]) ?>" title="Edit or Assign Task" aria-label="Edit or Assign Task" data-pjax="0"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="<?= \yii\helpers\Url::to(['order/view', 'id' => $o->id]) ?>" title="View Order Details" aria-label="View Order Details" data-pjax="0"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

crm/backend/views/order/process.php
<?php
use backend\util\Help;

$this->title = 'Process Orders';
#$this->params['breadcrumbs'][] = ['label' => 'Dashboard', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = 'Dashboard';

$progressOrders = \common\models\Orders::find()->where(['status'=>'in_progress'])->all();
?>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">In-Process Orders List</h4>
        <div class="table-responsive">
            <table class="table color-bordered-table warning-bordered-table">
                <thead>
                <tr>
                    <th>Order #</th>
                    <th>Customer Name</th>
                    <th>Writer</th>
                    <th>Subject Area</th>
                    <th>Remaining</th>
                    <th>Writer Deadline</th>
                    <th>Pages</th>
                    <th>Customer Deadline</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($progressOrders as $o): ?>
                <tr>
                    <td><?= $o->id ?></td>
                    <td><?= $o->customer->name ?></td>
                    <td><?= $o->writerTasks[0]->writer->full_name ?></td>
                    <td><?= $o->subjectArea->name ?></td>
                    <td><?= Help::getRemainingDays($o->writer_deadline) ?></td>
                    <td><?= $o->writer_deadline ?></td>
                    <td><?= $o->noPages->name ?></td>
                    <td><?= Help::getCustomerDealLine($o->urgency_id) ?></td>
                    <td><span class="badge badge-success"><?= $o->status ?></span></td>
                    <td><a href="<?= \yii\helpers\Url::to(['order/assign-update', 'id' => $o->id]) ?>" title="Change Assigning Details" aria-label="Change Assigning Details" data-pjax="0"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="<?= \yii\helpers\Url::to(['order/view', 'id' => $o->id]) ?>" title="View Order Details" aria-label="View Order Details" data-pjax="0"><span class="glyphicon glyphicon-eye-open"></span></a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

crm/backend/views/order/view.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;


$this->title = 'Order View #'.$id;
$this->params['breadcrumbs'][] = ['label' => 'Dashboard', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Basic Order Information</h4>
        <table class="table color-bordered-table success-bordered-table">
            <tr>
                <th>Order Id</th>
                <td><?=$o->id?></td>
            </tr>
            <tr>
                <th>Paper Type</th>
                <td><?=$o->paperType->name?></td>
            </tr>
                <th>Service Type</th>
                <td><?=$o->serviceType->name?></td>
            </tr>
            <tr>
                <th>Order Date</th>
                <td><?=$o->order_date?></td>
            </tr>
            <tr>
                <th>Urgency</th>
                <td><?=$o->urgency->name?></td>
            </tr>
            <tr>
                <th>Customer Deadline</th>
                <td><?=\backend\util\Help::getCustomerDealLine($o->urgency_id)?></td>
            </tr>
            <tr>
                <th>Quality</th>
                <td><?=$o->quality->name?></td>
            </tr>
            <tr>
                <th>Num of Pages</th>
                <td><?=$o->noPages->name?></td>
            </tr>
            <tr>
                <th>Subject</th>
                <td><?=$o->subjectArea->name?></td>
            </tr>
            <tr>
                <th>Topic</th>
                <td><?=$o->topic?></td>
            </tr>
            <tr>
                <th>Level</th>
                <td><?=$o->acadamicLevel->name?></td>
            </tr>
            <tr>
                <th>Writing Style</th>
                <td><?=$o->writingStyle->name?></td>
            </tr>
            <tr>
                <th>Language</th>
                <td><?=$o->language?></td>
            </tr>
            <tr>
                <th>Description</th>
                <td><?=$o->instructions?></td>
            </tr>


        </table>
        <div class="form-group">
            <?= Html::a('Task Assigning Detail', ['/order/writer-assign','id'=>$o->id], ['class'=>'btn btn-success btn-size-small']) ?>
            <?= Html::a('Edit this Order', ['/order/edit','id'=>$o->id], ['class'=>'btn btn-success btn-size-small']) ?>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
    <h4 class="card-title">Client Information - Order # <?=$id?></h4>
        <table class="table color-bordered-table success-bordered-table">
            <tr>
                <th>Client Id</th>
                <td><?=$c->id?></td>
            </tr>
            <tr>
                <th>Customer Name</th>
                <td><?=$c->name?></td>
            </tr>
                <th>Customer Email</th>
                <td><?=$c->email?></td>
            </tr>
            <tr>
                <th>Customer Phone</th>
                <td><?=$c->phone?></td>
            </tr>
            <tr>
                <th>Customer IP</th>
                <td><?=$c->ip?></td>
            </tr>
            <tr>
                <th>Customer IP-City</th>
                <td><?=$c->city?></td>
            </tr>
            <tr>
                <th>Customer IP-Region</th>
                <td><?=$c->region?></td>
            </tr>
            <tr>
                <th>Customer IP-Country</th>
                <td><?=$c->country?></td>
            </tr>
            <tr>
                <th>Customer Registration </th>
                <td><?=$c->created_at?></td>
            </tr>


        </table>

    </div>
</div>
<?php if($t):?>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Payment Information - Order # <?=$id?></h4>
        <table class="table color-bordered-table success-bordered-table">
            <thead>
            <tr>
                <th>Invoice ID</th>
                <th>Method</th>
                <th>Transaction Ref</th>
                <th>Payee Name</th>
                <th>Pay Date</th>
                <th>Status</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?=$t->id?></td>
                <td><?=$t->payment_method?></td>
                <td><?=$t->transaction_id?></td>
                <td><?=$t->payee_name?></td>
                <td><?=$t->payment_date?></td>
                <td><span class="badge badge-<?=($t->status == 'Paid')?'success':'warning'?>"><?=$t->status?></span></td>
                <td><?=$t->payee_amount?></td>

            </tr>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>